-- Final batch: Sub-Saharan Africa and remaining countries (ASCII only)

INSERT INTO snapshot_administrative_divisions (name, slug, country_id)
-- South Africa provinces
SELECT 'Gauteng', 'za-gauteng', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'Western Cape', 'za-western-cape', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'KwaZulu-Natal', 'za-kwazulu-natal', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'Eastern Cape', 'za-eastern-cape', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'Limpopo', 'za-limpopo', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'Mpumalanga', 'za-mpumalanga', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'North West', 'za-north-west', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'Free State', 'za-free-state', id FROM snapshot_countries WHERE slug = 'south-africa'
UNION ALL SELECT 'Northern Cape', 'za-northern-cape', id FROM snapshot_countries WHERE slug = 'south-africa'
-- Nigeria top states
UNION ALL SELECT 'Lagos', 'ng-lagos', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Kano', 'ng-kano', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Kaduna', 'ng-kaduna', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Oyo', 'ng-oyo', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Rivers', 'ng-rivers', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Bayelsa', 'ng-bayelsa', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Delta', 'ng-delta', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Anambra', 'ng-anambra', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Imo', 'ng-imo', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Abia', 'ng-abia', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Cross River', 'ng-cross-river', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Akwa Ibom', 'ng-akwa-ibom', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Enugu', 'ng-enugu', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Edo', 'ng-edo', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Ondo', 'ng-ondo', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Osun', 'ng-osun', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Ogun', 'ng-ogun', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Kwara', 'ng-kwara', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Plateau', 'ng-plateau', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Borno', 'ng-borno', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Adamawa', 'ng-adamawa', id FROM snapshot_countries WHERE slug = 'nigeria'
UNION ALL SELECT 'Abuja', 'ng-abuja', id FROM snapshot_countries WHERE slug = 'nigeria'
-- Kenya top counties
UNION ALL SELECT 'Nairobi City', 'ke-nairobi-city', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Kiambu', 'ke-kiambu', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Nakuru', 'ke-nakuru', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Machakos', 'ke-machakos', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Meru', 'ke-meru', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Kisumu', 'ke-kisumu', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Uasin Gishu', 'ke-uasin-gishu', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Kakamega', 'ke-kakamega', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Mombasa', 'ke-mombasa', id FROM snapshot_countries WHERE slug = 'kenya'
UNION ALL SELECT 'Kilifi', 'ke-kilifi', id FROM snapshot_countries WHERE slug = 'kenya'
-- Canada provinces
UNION ALL SELECT 'Alberta', 'ca-alberta', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'British Columbia', 'ca-british-columbia', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Manitoba', 'ca-manitoba', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'New Brunswick', 'ca-new-brunswick', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Newfoundland and Labrador', 'ca-newfoundland-and-labrador', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Northwest Territories', 'ca-northwest-territories', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Nova Scotia', 'ca-nova-scotia', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Nunavut', 'ca-nunavut', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Ontario', 'ca-ontario', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Prince Edward Island', 'ca-prince-edward-island', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Quebec', 'ca-quebec', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Saskatchewan', 'ca-saskatchewan', id FROM snapshot_countries WHERE slug = 'canada'
UNION ALL SELECT 'Yukon', 'ca-yukon', id FROM snapshot_countries WHERE slug = 'canada'
-- US top states
UNION ALL SELECT 'California', 'us-california', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Texas', 'us-texas', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Florida', 'us-florida', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'New York', 'us-new-york', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Pennsylvania', 'us-pennsylvania', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Illinois', 'us-illinois', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Ohio', 'us-ohio', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Georgia', 'us-georgia', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'North Carolina', 'us-north-carolina', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Michigan', 'us-michigan', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'New Jersey', 'us-new-jersey', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Virginia', 'us-virginia', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Washington', 'us-washington', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Arizona', 'us-arizona', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Tennessee', 'us-tennessee', id FROM snapshot_countries WHERE slug = 'united-states'
UNION ALL SELECT 'Massachusetts', 'us-massachusetts', id FROM snapshot_countries WHERE slug = 'united-states'
ON CONFLICT (country_id, slug) DO NOTHING;