-- First, let's rename the cities table to better reflect administrative divisions
ALTER TABLE snapshot_cities RENAME TO snapshot_administrative_divisions;

-- Clear existing data to start fresh with the comprehensive mapping
DELETE FROM snapshot_administrative_divisions;
DELETE FROM snapshot_countries;
DELETE FROM snapshot_geographic_regions;

-- Insert the 6 main regions
INSERT INTO snapshot_geographic_regions (name, slug) VALUES
('Asia Pacific', 'asia-pacific'),
('Emerging Asia', 'emerging-asia'),
('Europe', 'europe'),
('Latin America', 'latin-america'),
('Middle East & Africa', 'middle-east-africa'),
('North America', 'north-america');

-- Get region IDs for reference
WITH region_ids AS (
  SELECT id, name FROM snapshot_geographic_regions
)

-- Insert all countries with their region relationships
INSERT INTO snapshot_countries (name, slug, region_id)
SELECT country, LOWER(REPLACE(REPLACE(REPLACE(country, ' ', '-'), '(', ''), ')', '')), region_ids.id
FROM (VALUES
  -- Asia Pacific
  ('Australia', 'Asia Pacific'),
  ('Brunei', 'Asia Pacific'),
  ('Cook Islands', 'Asia Pacific'),
  ('Fiji', 'Asia Pacific'),
  ('French Polynesia', 'Asia Pacific'),
  ('Hong Kong', 'Asia Pacific'),
  ('Japan', 'Asia Pacific'),
  ('Kiribati', 'Asia Pacific'),
  ('Macau', 'Asia Pacific'),
  ('Marshall Islands', 'Asia Pacific'),
  ('Micronesia', 'Asia Pacific'),
  ('Nauru', 'Asia Pacific'),
  ('New Caledonia', 'Asia Pacific'),
  ('New Zealand', 'Asia Pacific'),
  ('Palau', 'Asia Pacific'),
  ('Papua New Guinea', 'Asia Pacific'),
  ('Samoa', 'Asia Pacific'),
  ('Singapore', 'Asia Pacific'),
  ('Solomon Islands', 'Asia Pacific'),
  ('South Korea', 'Asia Pacific'),
  ('Taiwan', 'Asia Pacific'),
  ('Tonga', 'Asia Pacific'),
  ('Tuvalu', 'Asia Pacific'),
  ('Vanuatu', 'Asia Pacific'),
  
  -- Emerging Asia
  ('Afghanistan', 'Emerging Asia'),
  ('Bangladesh', 'Emerging Asia'),
  ('Bhutan', 'Emerging Asia'),
  ('Cambodia', 'Emerging Asia'),
  ('China', 'Emerging Asia'),
  ('East Timor (Timor-Leste)', 'Emerging Asia'),
  ('India', 'Emerging Asia'),
  ('Indonesia', 'Emerging Asia'),
  ('Kazakhstan', 'Emerging Asia'),
  ('Kyrgyzstan', 'Emerging Asia'),
  ('Laos', 'Emerging Asia'),
  ('Malaysia', 'Emerging Asia'),
  ('Maldives', 'Emerging Asia'),
  ('Mongolia', 'Emerging Asia'),
  ('Myanmar', 'Emerging Asia'),
  ('Nepal', 'Emerging Asia'),
  ('North Korea', 'Emerging Asia'),
  ('Pakistan', 'Emerging Asia'),
  ('Philippines', 'Emerging Asia'),
  ('Sri Lanka', 'Emerging Asia'),
  ('Tajikistan', 'Emerging Asia'),
  ('Thailand', 'Emerging Asia'),
  ('Turkmenistan', 'Emerging Asia'),
  ('Uzbekistan', 'Emerging Asia'),
  ('Vietnam', 'Emerging Asia'),
  
  -- Europe
  ('Albania', 'Europe'),
  ('Andorra', 'Europe'),
  ('Armenia', 'Europe'),
  ('Austria', 'Europe'),
  ('Azerbaijan', 'Europe'),
  ('Belarus', 'Europe'),
  ('Belgium', 'Europe'),
  ('Bosnia and Herzegovina', 'Europe'),
  ('Bulgaria', 'Europe'),
  ('Croatia', 'Europe'),
  ('Cyprus', 'Europe'),
  ('Czech Republic', 'Europe'),
  ('Denmark', 'Europe'),
  ('Estonia', 'Europe'),
  ('Finland', 'Europe'),
  ('France', 'Europe'),
  ('Georgia', 'Europe'),
  ('Germany', 'Europe'),
  ('Greece', 'Europe'),
  ('Hungary', 'Europe'),
  ('Iceland', 'Europe'),
  ('Ireland', 'Europe'),
  ('Italy', 'Europe'),
  ('Kosovo', 'Europe'),
  ('Latvia', 'Europe'),
  ('Liechtenstein', 'Europe'),
  ('Lithuania', 'Europe'),
  ('Luxembourg', 'Europe'),
  ('Malta', 'Europe'),
  ('Moldova', 'Europe'),
  ('Monaco', 'Europe'),
  ('Montenegro', 'Europe'),
  ('Netherlands', 'Europe'),
  ('North Macedonia', 'Europe'),
  ('Norway', 'Europe'),
  ('Poland', 'Europe'),
  ('Portugal', 'Europe'),
  ('Romania', 'Europe'),
  ('Russia', 'Europe'),
  ('San Marino', 'Europe'),
  ('Serbia', 'Europe'),
  ('Slovakia', 'Europe'),
  ('Slovenia', 'Europe'),
  ('Spain', 'Europe'),
  ('Sweden', 'Europe'),
  ('Switzerland', 'Europe'),
  ('Turkey', 'Europe'),
  ('Ukraine', 'Europe'),
  ('United Kingdom', 'Europe'),
  ('Vatican City (Holy See)', 'Europe'),
  
  -- Latin America
  ('Antigua and Barbuda', 'Latin America'),
  ('Anguilla', 'Latin America'),
  ('Argentina', 'Latin America'),
  ('Aruba', 'Latin America'),
  ('Bahamas', 'Latin America'),
  ('Barbados', 'Latin America'),
  ('Belize', 'Latin America'),
  ('Bermuda', 'Latin America'),
  ('Bolivia', 'Latin America'),
  ('Brazil', 'Latin America'),
  ('Cayman Islands', 'Latin America'),
  ('Chile', 'Latin America'),
  ('Colombia', 'Latin America'),
  ('Costa Rica', 'Latin America'),
  ('Cuba', 'Latin America'),
  ('Curaçao', 'Latin America'),
  ('Dominica', 'Latin America'),
  ('Dominican Republic', 'Latin America'),
  ('Ecuador', 'Latin America'),
  ('El Salvador', 'Latin America'),
  ('Grenada', 'Latin America'),
  ('Guatemala', 'Latin America'),
  ('Guyana', 'Latin America'),
  ('Haiti', 'Latin America'),
  ('Honduras', 'Latin America'),
  ('Jamaica', 'Latin America'),
  ('Montserrat', 'Latin America'),
  ('Nicaragua', 'Latin America'),
  ('Panama', 'Latin America'),
  ('Paraguay', 'Latin America'),
  ('Peru', 'Latin America'),
  ('Puerto Rico', 'Latin America'),
  ('Saint Kitts and Nevis', 'Latin America'),
  ('Saint Lucia', 'Latin America'),
  ('Saint Vincent and the Grenadines', 'Latin America'),
  ('Sint Maarten', 'Latin America'),
  ('Suriname', 'Latin America'),
  ('Trinidad and Tobago', 'Latin America'),
  ('Turks and Caicos Islands', 'Latin America'),
  ('Uruguay', 'Latin America'),
  ('Venezuela', 'Latin America'),
  
  -- Middle East & Africa
  ('Algeria', 'Middle East & Africa'),
  ('Angola', 'Middle East & Africa'),
  ('Bahrain', 'Middle East & Africa'),
  ('Benin', 'Middle East & Africa'),
  ('Botswana', 'Middle East & Africa'),
  ('Burkina Faso', 'Middle East & Africa'),
  ('Burundi', 'Middle East & Africa'),
  ('Cameroon', 'Middle East & Africa'),
  ('Cape Verde (Cabo Verde)', 'Middle East & Africa'),
  ('Central African Republic', 'Middle East & Africa'),
  ('Chad', 'Middle East & Africa'),
  ('Comoros', 'Middle East & Africa'),
  ('Congo', 'Middle East & Africa'),
  ('Djibouti', 'Middle East & Africa'),
  ('DR Congo', 'Middle East & Africa'),
  ('Egypt', 'Middle East & Africa'),
  ('Equatorial Guinea', 'Middle East & Africa'),
  ('Eritrea', 'Middle East & Africa'),
  ('Eswatini', 'Middle East & Africa'),
  ('Ethiopia', 'Middle East & Africa'),
  ('Gabon', 'Middle East & Africa'),
  ('Gambia', 'Middle East & Africa'),
  ('Ghana', 'Middle East & Africa'),
  ('Guinea', 'Middle East & Africa'),
  ('Guinea-Bissau', 'Middle East & Africa'),
  ('Iran', 'Middle East & Africa'),
  ('Iraq', 'Middle East & Africa'),
  ('Israel', 'Middle East & Africa'),
  ('Ivory Coast (Côte d''Ivoire)', 'Middle East & Africa'),
  ('Jordan', 'Middle East & Africa'),
  ('Kenya', 'Middle East & Africa'),
  ('Kuwait', 'Middle East & Africa'),
  ('Lebanon', 'Middle East & Africa'),
  ('Lesotho', 'Middle East & Africa'),
  ('Liberia', 'Middle East & Africa'),
  ('Libya', 'Middle East & Africa'),
  ('Madagascar', 'Middle East & Africa'),
  ('Malawi', 'Middle East & Africa'),
  ('Mali', 'Middle East & Africa'),
  ('Mauritania', 'Middle East & Africa'),
  ('Mauritius', 'Middle East & Africa'),
  ('Morocco', 'Middle East & Africa'),
  ('Mozambique', 'Middle East & Africa'),
  ('Namibia', 'Middle East & Africa'),
  ('Niger', 'Middle East & Africa'),
  ('Nigeria', 'Middle East & Africa'),
  ('Oman', 'Middle East & Africa'),
  ('Palestine', 'Middle East & Africa'),
  ('Qatar', 'Middle East & Africa'),
  ('Rwanda', 'Middle East & Africa'),
  ('São Tomé and Príncipe', 'Middle East & Africa'),
  ('Saudi Arabia', 'Middle East & Africa'),
  ('Senegal', 'Middle East & Africa'),
  ('Seychelles', 'Middle East & Africa'),
  ('Sierra Leone', 'Middle East & Africa'),
  ('Somalia', 'Middle East & Africa'),
  ('South Africa', 'Middle East & Africa'),
  ('South Sudan', 'Middle East & Africa'),
  ('Sudan', 'Middle East & Africa'),
  ('Syria', 'Middle East & Africa'),
  ('Tanzania', 'Middle East & Africa'),
  ('Togo', 'Middle East & Africa'),
  ('Tunisia', 'Middle East & Africa'),
  ('UAE (United Arab Emirates)', 'Middle East & Africa'),
  ('Uganda', 'Middle East & Africa'),
  ('Yemen', 'Middle East & Africa'),
  ('Zambia', 'Middle East & Africa'),
  ('Zimbabwe', 'Middle East & Africa'),
  
  -- North America
  ('Canada', 'North America'),
  ('Greenland', 'North America'),
  ('Mexico', 'North America'),
  ('United States', 'North America')
) AS countries(country, region)
JOIN region_ids ON region_ids.name = countries.region;