// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaykakhcobkdqycqvypy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlheWtha2hjb2JrZHF5Y3F2eXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzcxNjksImV4cCI6MjA3MTAxMzE2OX0.xSDkjHXV4Jt3pGwtNXuuXOB6B22Nj66bAjr6v7Tftis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});